### ISSUE TITLE
Where do I store files?

### ISSUE THREAD

**Issue by jbrooksuk** [ejholmes/vagrant-heroku#13]
This may sound really stupid, but where do I put files, and how do I access them? I don't see a `public` folder, or anything in the README which explains actual usage of it.

**Comment by slopezm** [comment]
Vagrant creates a shared folder inside the Heroku box which can be accessed via /vagrant. It contains all the files in your project's local directory (where your Vagrantfile is located). Take a look at "Accessing Project Files" at http://docs.vagrantup.com/v1/docs/getting-started/ssh.html for more information.

**Comment by jbrooksuk** [comment]
Ah I see, sorry, when I've setup a Vagrant box before, I've had a separate directory for code. Cheers :)
