### ISSUE TITLE
Include postgres-contrib

### ISSUE THREAD

**Issue by emckenna** [ejholmes/vagrant-heroku#20]
Trying to use pg_search gem, and I'm unable to get the extensions correctly loaded.
basically this: https://github.com/Casecommons/pg_search/wiki/Installing-Postgres-Contrib-Modules

I've tried just doing 'apt-get install postgres-contrib', but it starts adding another set of config files and such under /usr/share/postgresql/ making things real confusing.

**Comment by ejholmes** [comment]
Hmm, maybe we should just [`apt-get install postgres postgres-contrib` instead](https://github.com/ejholmes/vagrant-heroku/blob/master/definitions/heroku/postinstall.sh#L67)?

Either that, or build postgres-contrib from source. I'll look into it, thanks!

**Comment by emckenna** [comment]
I'm in the middle of trying a workaround by removing the existing postgres install, and the going the apt-get route. After updating to 9.1 with apt-get, I tried to get postgres-contrib but i'm then prompted to upgrade to postgresql 9.2, heh.  I'll post back if i get it working with the extensions.

**Comment by ejholmes** [comment]
Awesome. Thanks!

**Comment by emckenna** [comment]
OK, here's how i got it working.
- stop postgres - <pre>sudo su postgres -c 'pg_ctl stop -D /var/pgsql/data'</pre>
- locate postgres directories, remove all the files (locate postgres | xargs sudo rm -rf)
  this could be a bad idea
- get 9.1 from http://www.postgresql.org/download/linux/ubuntu/
- Create the file /etc/apt/sources.list.d/pgdg.list, and add a line for the repository
- add <pre>deb http://apt.postgresql.org/pub/repos/apt/ lucid-pgdg main</pre>
- Import the repository signing key, and update the package lists
  <pre>wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -</pre>
  <pre>sudo apt-get update</pre>
- install postgres
  <pre>sudo apt-get install postgresql-9.1</pre>
  <pre>sudo apt-get install postgresql-contrib-9.1</pre>
- my bundle install was failing on pg gem so
  <pre>sudo apt-get install libpq-dev</pre>

Now you should be able to log into postgres and run the CREATE EXTENSION commands
<pre>postgres=# CREATE EXTENSION pg_trgm;
CREATE EXTENSION
postgres=# \dx
                                    List of installed extensions
  Name   | Version |   Schema   |                            Description
---------+---------+------------+-------------------------------------------------------------------
 pg_trgm | 1.0     | public     | text similarity measurement and index searching based on trigrams
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)<pre>

**Comment by emckenna** [comment]
doh! didn't mean to close it.

**Comment by ejholmes** [comment]
Cool. I'll see if I can get this scripted in [postinstall.sh](https://github.com/ejholmes/vagrant-heroku/blob/master/definitions/heroku/postinstall.sh) sometime this weekend.

**Comment by davetapley** [comment]
@emckenna FYI, instead of:

> locate postgres directories, remove all the files (locate postgres | xargs sudo rm -rf) this could be a bad idea

You can download, extract, and `./configure --prefix=/usr` `postgresql-9.1.5` again, then you can `sudo make uninstall` to get a clean removal :smiley:

**Comment by HotFusionMan** [comment]
I submitted a pull request containing a one-word addition to postinstall.sh that, according to the PostgreSQL docs, will build all the contrib extensions supplied with the official PostgreSQL distro.
